### ISSUE TITLE
Resistance Perturbation fails on empty graph

### ISSUE THREAD

**Issue by sdmccabe** [netsiphd/netrd#140]
```python
>>> from netrd.distance import ResistancePerturbation
>>> import networkx as nx
>>> G = nx.empty_graph(100)
>>> ResistancePerturbation().dist(G, G)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/main/git/netrd/netrd/distance/resistance_perturbation.py", line 66, in dist
    R1 = get_resistance_matrix(G1)
  File "/home/main/git/netrd/netrd/distance/resistance_perturbation.py", line 105, in get_resistance_matrix
    L_i = np.linalg.solve(L+J, I) - J
  File "/home/main/.pyenv/versions/miniconda3-latest/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 394, in solve
    r = gufunc(a, b, signature=signature, extobj=extobj)
  File "/home/main/.pyenv/versions/miniconda3-latest/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 89, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.linalg.LinAlgError: Singular matrix
```

**Comment by leotrs** [comment]
It makes sense that it errors out on that line as it's trying to invert a matrix of all zeros. What do we want to do here? What comes to mind is to error out but earlier and with a nicer message?

**Comment by sdmccabe** [comment]
I don't have a strong feeling on if it's even a thing we *need* to fix; I just came across when while writing a test for the third Deltacon condition. 

I see three possibilities:

1. Do nothing.
2. Test for empty graphs and raise a ValueError (and mention in the docstring that it doesn't work on empty graphs).
3. NumPy recommends falling back on on `lstsq` if `solve` is inappropriate. I don't know what knock-on effects this would have, though. I think I tried handling the exception that way on my own system and wound up with a divide-by-zero case and a final distance of  `nan`.

**Comment by sdmccabe** [comment]
Worth noting that it's not just the empty graph, since the matrix is still singular if you add a dyad (as @leotrs mentioned as a possible modification of the Deltacon third test in #139.)

**Comment by leotrs** [comment]
Good catch on dyads also erroring. I'd say we either do nothing or we start validating inputs everywhere.

I vote for nothing.

**Comment by sdmccabe** [comment]
I tend to agree. A bunch of the methods misbehave on empty graphs and (for now at least) we're not validating those either. 

The dyad case points to a more general concern about the method breaking on all singular adjacency matrices; I _think_ those are sufficiently rare that we can just not deal with it. (Actually, how rare are they? I don't have strong priors on this.)

**Comment by sdmccabe** [comment]
Going to close this. If singular adjacency matrices suddenly start rising up and attacking us, we have an idea of where the problem is.
