### ISSUE TITLE
NetLSD

### ISSUE THREAD

**Issue by xgfs** [netsiphd/netrd#146]
Hey!
It's a really nice codebase that you have created. We had a paper at last KDD on comparing graphs, maybe it's worth to be added here? I have published the code under MIT license at [xgfs/NetLSD](https://github.com/xgfs/NetLSD), it vaguely follows the framework here. Would it be welcome?

I am not sure what is the contributing guide for people outside Northeastern.

**Comment by tlarock** [comment]
Thanks for reaching out - NetLSD seems cool, and I think I might have actually seen your talk on it at KDD (very memorable title)! The short answer is yes, your contribution would be totally welcome!

We do have a bunch of spectral methods already implemented (cc @gstonge) here: https://github.com/netsiphd/netrd/blob/master/netrd/distance/laplacian_spectral_method.py 

It seems like your NetLSD code adds a couple of kernels we don't have implemented yet. Would the minimal effort contribution be to 1) add your kernels to `laplacian_spectral_method.py` and 2) add an option to return the distance between NetLSD descriptors? And of course add your paper to the citations.

It would also probably be fine to have NetLSD be it's own separate class if you'd prefer, but if it is possible to have most of the Laplacian computations be done in the already existing class that might be best.

**Comment by gstonge** [comment]
This is a really cool method, I really like the idea of the heat kernel! Although related to the Laplacian matrix, the way the graph distance is computed seems quite different from the ones in `laplacian_spectral_method.py`. I think it would be better to let NetLSD be it's own separate class.

**Comment by tlarock** [comment]
Thanks @gstonge! 

It seems like it should be fairly straightforward to convert what is already at [NetLSD](https://github.com/xgfs/NetLSD) to the `netrd` framework. The main steps are to 
1) Convert `kernel.py` to a class called `NetLSD` in `net_lsd.py`. Include all `util.py` functions in the class. If available, change code to use functions already implemented in `netrd` to avoid redundancy.
2) Merge the `compare()` and `netlsd()` functions from the file formerly known as `kernel.py` and change the name to `dist()`
2a) Update the function call to accept standard parameters where possible and return only the distance between the computed signatures.
2b) Add code to populate the `self.results` dictionary.
3) Add `from .net_lsd import NetLSD` to `netrd/distances/__init__.py`
4) Test, then submit a pull request!

Not going to assign this issue, but anyone who is watching is welcome to work on it! And @xgfs if you'd like to do it yourself just let us know if you need any guidance!

**Comment by xgfs** [comment]
I will work on it later this week :)
I'll poke the thread with the pull request ready
