### ISSUE TITLE
Resistance perturbation fails on disconnected graphs

### ISSUE THREAD

**Issue by sdmccabe** [netsiphd/netrd#158]
The resistance matrix is undefined for disconnected graphs, which is what leads to distances of 1e17 that we encounter in some of our experiments. It seems fairly straightforward to make this an exception to be handled in our experiments scripts rather than silently returning a meaningless result.

See also #140 on input validation, though.

**Comment by tlarock** [comment]
We could have it instead throw a warning and compare the largest connected components.

**Comment by sdmccabe** [comment]
Resistance perturbation is designed to compare dynamic snapshots of the same graph; i.e., it assumes the node labels are the same. So we should use ValueError approach that's in #163. (Really, it could be stricter; we could additionally require identical node sets.)
