### ISSUE TITLE
Interface for normalizing to distributions

### ISSUE THREAD

**Issue by sdmccabe** [netsiphd/netrd#166]
To avoid unnecessary error, we should make sure that we have consistent interfaces for constructing histograms, normalizing vectors to sum to one, etc. This is an easy case for `utilities/`.

**Comment by leotrs** [comment]
What's the use case for this? And how does it relate to #174?

**Comment by sdmccabe** [comment]
The logic was to provide consistency in how we're converting sequences to histograms; e.g., in #178 you replaced a bespoke internal function for doing this with `list(dict(G.degree).values())` or something similar. I don't feel strongly about enforcing this everywhere - my mistake with degree divergence aside, I think this is pretty straightforward to do - and the issue was mostly about putting it on the agenda for last week's mini-hackathon. Feel free to close this.
