### ISSUE TITLE
num_eigs=10 does not permit time series with fewer than 10 nodes @sdmccabe

### ISSUE THREAD

**Issue by jkbren** [netsiphd/netrd#17]
https://github.com/netsiphd/netrd/blob/096387da564e77c459b636f0e13501b55e210e18/netrd/reconstruction/correlation_matrix.py#L18

**Comment by leotrs** [comment]
This came up because we were testing the correlation matrix reconstructor on a time series with two identical rows. What should be the outcome in this case? We may add this as a test.

**Comment by sdmccabe** [comment]
I don't know what the outcome should be. (The nodes should have identical edges?)

As for `num_eigs`, my instinct is to just raise a `ValueError` if `num_eigs` is less than (what will become) the number of nodes in the graph.

**Comment by leotrs** [comment]
> As for num_eigs, my instinct is to just raise a ValueError if num_eigs is less than (what will become) the number of nodes in the graph.
Agreed.
