### ISSUE TITLE
parameter in HIM distance

### ISSUE THREAD

**Issue by jkbren** [netsiphd/netrd#170]
we should understand how the default value of 1.0 affects the distance
<img width="1299" alt="Screen Shot 2019-05-07 at 10 32 59 AM" src="https://user-images.githubusercontent.com/15849294/57308008-8b4c4880-70b3-11e9-9ace-bb1f12f605ee.png">

**Comment by sdmccabe** [comment]
The paper does not give much guidance on what a default value of ζ should be. In its absence I think using 1.0 is fine. Maybe we could add a little more documentation, i.e., explicitly say if ζ=0 it's Hamming and as ζ approaches infinity it becomes IM, but I'm not sure what we can do past that.

**Comment by leotrs** [comment]
I don't think there's much more to say other than the fact that HIM is the square root (why?) of the weighted average of H² and IM², and ξ is the ratio of the weights. ξ=1 corresponds to equal weights.

Does anyone know (1) why they take the square root, or (2) why @sdmccabe wrote ζ instead of ξ?

**Comment by sdmccabe** [comment]
For (2), it’s because I can’t read.

**Comment by hartle** [comment]
My guess is that the square root is to make it (proportional to) the Euclidean length of a vector with components H and (√ξ)IM. Another way to read it that looks a bit better is (1+ξ)(HIM)²=H²+ξ(IM)².
