### ISSUE TITLE
Time Granger Causality - confirm implementation

### ISSUE THREAD

**Issue by sdmccabe** [netsiphd/netrd#172]
![image](https://user-images.githubusercontent.com/10427730/57314643-103d5f00-70c0-11e9-9dc0-b9e0ef6bd6ac.png)
We don't have a ton of confidence in the TGC implementation. It's fine if it performs poorly (though Sherrington-Kirkpatrick dynamics on a ring of cliques should be an easy case), but more concerning is the streak-like pattern observed in the weights matrix some nodes are very active and others not.

**Comment by leotrs** [comment]
Pinging author @charlesmurphy1

**Comment by hartle** [comment]
The same streak-like pattern is observed in the column corresponding to nodes 38-48, but as a streak of smaller-than-usual values as opposed to larger-than-usual. Is that a natural consequence of TGC, or another oddity?

I assume there's nothing "special" about those nodes, seeing as the ring of cliques is symmetrical. If so, then as the simulation duration grows, the TGC result should become more symmetrical also as dynamical fluctuations become less important.

**Comment by leotrs** [comment]
Any updates on this? It'd be nice to close this before NetSci @hartle @charlesmurphy1
