### ISSUE TITLE
DeprecationWarning in Jaccard distance

### ISSUE THREAD

**Issue by sdmccabe** [netsiphd/netrd#180]
From running the tests locally (also seen in Travis):

> tests/test_distance.py::test_symmetry
  /home/main/.pyenv/versions/miniconda3-latest/lib/python3.6/site-packages/sklearn/metrics/classification.py:635: DeprecationWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
    'and multiclass classification tasks.', DeprecationWarning)

**Comment by sdmccabe** [comment]
Jaccard is sufficiently simple that we might consider implementing it ourselves for this. The other possibilities are to try/except our way around this deprecation or to bump our sklearn dependency to something much newer than our other requirements.

**Comment by leotrs** [comment]
Why not use `jaccard_score` instead of our own implementation?

**Comment by sdmccabe** [comment]
My concern had been that `jaccard_score` was a recent addition, but our scipy requirement is actually newer than that so we should try using `jaccard_score` first.
