### ISSUE TITLE
can we add threshold to ConvergentCrossMapping

### ISSUE THREAD

**Issue by jkbren** [netsiphd/netrd#182]
https://github.com/netsiphd/netrd/blob/2bf59179da12cd203b0f242cb73cfa59f5c1b9b2/netrd/reconstruction/convergent_cross_mapping.py#L124

**Comment by chiahungyang** [comment]
Yes I can definitely do that. Question: Shall we threshold on correlation between estimates and actual time series, or threshold on the _p_-values from statistical tests of correlation?

**Comment by leotrs** [comment]
Not an expert but I vote we threshold on correlation due to no particular reason.
