### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by leotrs** [netsiphd/netrd#196]
Now that RTD is [up and running](https://netrd.readthedocs.io/en/latest/) it will be easy to iterate over the documentation a few cycles to improve it.

Wishlist:

- [ ] have a big table listing all distances and whether or not they are metrics
- [x] add a short tutorial
- [x] fix the utilities page
- [ ] list each author's name alongside each class/file

**Comment by leotrs** [comment]
On the Big Table: the [docs](https://netrd.readthedocs.io/en/latest/distance.html) now have a table but it doesn't say whether each distance is a metric or not. Do we actually want to do that? How many of them actually are metrics? I think most of them will say "pseudo-metric" or "unknown". 

Showing the author's name will probably take a bit of code spelunking, including possibly tampering with jinja templates. Is this worth it? Also, we should have a contributor list in README.md or in a separate CONTRIBUTORS.md.

**Comment by sdmccabe** [comment]
The Big Table requires us to address #174. If we aren't doing that before NetSci we should punt the Big Table to after NetSci.

**Comment by sdmccabe** [comment]
I think CONTRIBUTORS is probably the best approach here. Is it possible to mirror CONTRIBUTORS into RTD?

**Comment by leotrs** [comment]
Yes it's not hard to include an external file in the documentation.

**Comment by leotrs** [comment]
I think we can close this. Don't think we'll be doing the Big Table any time soon tbh.
