### ISSUE TITLE
Voter dynamics needs more random restarts

### ISSUE THREAD

**Issue by jkbren** [netsiphd/netrd#216]

**Comment by sdmccabe** [comment]
The voter model has `noise=None` by default to be the "true" voter model. The amount of noise that seemed to work best was around 1/N which is graph dependent, so it's harder to set an appropriate value. We could change the meaning of `noise=None` to mean something other than `noise=0`.

**Comment by sdmccabe** [comment]
Should we change the default behavior of `noise` here or move on?

**Comment by leotrs** [comment]
We could add a `noise='automatic'` option to mean `1/N`
