### ISSUE TITLE
Graph edit distances

### ISSUE THREAD

**Issue by sdmccabe** [netsiphd/netrd#227]
Perhaps we should have a more general NetSci postmortem, but one specific piece of feedback I got was a request for more graph edit distances. I think we avoided these because we already had Hamming distance, but we should definitely consider a more general GED implementation.

**Comment by leotrs** [comment]
First step is to compile a list of edit distances to implement. NetworkX has one, yes?

**Comment by sdmccabe** [comment]
[They do](https://networkx.github.io/documentation/latest/reference/algorithms/generated/networkx.algorithms.similarity.optimize_graph_edit_distance.html). Before the collabathon we had also flagged [this survey paper](https://link.springer.com/article/10.1007/s10044-008-0141-y) as potentially useful.

**Comment by leotrs** [comment]
Is this the kind of thing that we can implement a single monolithic edit distance and parameterize the hell out of it?

**Comment by sdmccabe** [comment]
Probably. That's what networkx does.

**Comment by sdmccabe** [comment]
Coming around to the idea that we should just not implement this. It would just be a wrapper around NetworkX's graph edit distance, and since this library is already built on top of NetworkX, the value-add is pretty low. The benefit is a consistent interface, but is that worth it? It's not like it's that complicated an interface anyway.

**Comment by leotrs** [comment]
Fair. I guess we can close this for now until there is demand?

**Comment by leotrs** [comment]
It also opens a whole nother can o worms: does `netrd` want to implement ALL distances, regardless of whether or not they are accessible through other means?

**Comment by sdmccabe** [comment]
I think it's a reasonable goal to have `netrd` implement as many as possible while acknowledging that _all_ is basically impossible.
