### ISSUE TITLE
Earth mover's distance and POT dependency

### ISSUE THREAD

**Issue by sdmccabe** [netsiphd/netrd#232]
Ideally we would deprecate the POT dependency and use ortools instead, since it's a headache for the `requirements.txt`

**Comment by leotrs** [comment]
To be totally fair, the problem comes from a bug in pypi, not pot, as documented [here](https://github.com/rflamary/POT/issues/59).

I agree the way to go is to replace POT.

**Comment by sdmccabe** [comment]
Related to the POT dependency is that we still have `==` in our requirements for Cython.

**Comment by leotrs** [comment]
There's been an update on [their side](https://github.com/rflamary/POT/pull/88), mostly on the documentation side of things. They closed their open issue, though it is unclear that their new PR actually solves our problem.
