### ISSUE TITLE
Tests are non-deterministic

### ISSUE THREAD

**Issue by sdmccabe** [netsiphd/netrd#239]
We hit an unexpected test failure in `test_directed_input`. The error was that one of the source graphs was disconnected. This was pretty unlikely, given the G(n,p) parameters, but it can happen, and because the tests do not fix `np.random.seed()` and `random.seed()`, it will probably pop up randomly from time to time and force us to restart Travis jobs.

**Comment by leotrs** [comment]
Two options:

+ fix the seed and run the tests always on the same graph so this doesn't happen, or
+ don't fix the seed and run the tests on always different graphs, and this will bite us maybe once every hundred tests.

I'd rather have the latter. It seems safer to run tests on more/different graphs. Maybe leave a big comment/warning somewhere about this so we're not scratching our heads when it happens again.

A further action is to see if py.test already has considered non-deterministic tests and we can force it to re-run a test if it fails at first.

**Comment by tlarock** [comment]
Think I agree with @leotrs here. Fixing the test to be on the same graph seems like an overreaction to a problem that is going to come up only very rarely. Can we just increase the connection probability to average degree 20 rather than 10? The parameter isn't super important, but I think having random graphs is a slightly better test.

**Comment by sdmccabe** [comment]
Works for me. I'll draw something up. We should probably mention this in the CONTRIBUTING?

**Comment by sdmccabe** [comment]
We don't actually mention running the tests locally in CONTRIBUTING, and any Travis failures can be addressed by us.

**Comment by sdmccabe** [comment]
#240 will deal with the density concern. Otherwise, we'll close this for now.
