### ISSUE TITLE
Clarify usage of utilities.entropy.entropy?

### ISSUE THREAD

**Issue by sdmccabe** [netsiphd/netrd#261]
When I was refactoring the Dmeasure code, I looked at using our version of entropy instead of scipy's, but one is not a drop-in replacement for the other because they take different inputs - one takes a histogram and the other takes a sequence of values. It would touch a lot of files but but renaming our `entropy` to something like `entropy_from_sequence` would remove this ambiguity.

**Comment by leotrs** [comment]
I like giving it a new name, doesn't matter it would touch many files

**Comment by sdmccabe** [comment]
`entropy_from_sequence` seems wordy but sufficiently explicit. Maybe `entropy_from_seq`? I'm led to believe that sequence entropy has its own meaning, so I don't think we could do `seq_entropy`.
