### ISSUE TITLE
VoterModel fails on graphs with negatively weighted edges

### ISSUE THREAD

**Issue by sdmccabe** [netsiphd/netrd#286]
```
In [72]: X = netrd.dynamics.VoterModel().simulate(G, 2001, noise=None)                                                                                                  
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-72-62a5f86360b7> in <module>
----> 1 X = netrd.dynamics.VoterModel().simulate(G, 2001, noise=None)

~/git/sdmccabe/netrd/netrd/dynamics/voter.py in simulate(self, G, L, noise)
     70             TS[:, t] = TS[:, t - 1]
     71             for i in indices:
---> 72                 TS[i, t] = np.random.choice(TS[:, t], p=transitions[:, i])
     73                 if np.random.rand() < noise:
     74                     TS[i, t] = 1 if np.random.rand() < 0.5 else -1

mtrand.pyx in numpy.random.mtrand.RandomState.choice()

ValueError: probabilities are not non-negative
```
The transition matrix is drawn from the adjacency matrix. NetworkX's `to_numpy_array()` has the default argument `weights='weight'`; so if you pass in a network with weighted edges, these will be included; if the network has negatively weighted edges, this will lead to negative transition probabilities. 

There are two solutions here:

1. Floor the transition matrix at zero.
2. Set `weights=None` in the call to `nx.to_numpy_array()`.

I think I prefer the second; I don't think even positive weights should be included here.

**Comment by leotrs** [comment]
Sounds like number 2. should make use of `ensure_unweighted`.
