### ISSUE TITLE
Portrait divergence: unclear if weighted graphs are supported

### ISSUE THREAD

**Issue by sdmccabe** [netsiphd/netrd#288]
PD converts to unweighted, then handles negative weights. The implication here is that it _should_ support weights.

```python
        G1 = ensure_unweighted(G1)
        G2 = ensure_unweighted(G2)

        adj1 = nx.to_numpy_array(G1)
        adj2 = nx.to_numpy_array(G2)

        ## NOTE dijkstra cannot handle negative weights
        if (adj1 < 0).any() or (adj2 < 0).any():
            adj1 = np.abs(adj1)
            adj2 = np.abs(adj2)
            G1 = nx.from_numpy_array(adj1)
            G2 = nx.from_numpy_array(adj2)
```

**Comment by sdmccabe** [comment]
The paper itself has an appendix on handling weighted graphs, and since the primary difference is using Dijkstra instead of BFS, I think this implementation should support weighted graphs.

**Comment by leotrs** [comment]
Let's support them

**Comment by sdmccabe** [comment]
Yeah, it should hopefully be an easy fix.
