### ISSUE TITLE
Handle short path lengths in polynomial dissimilarity

### ISSUE THREAD

**Issue by sdmccabe** [netsiphd/netrd#294]
In polynomial dissimilarity distance, if the graph has no paths of length less than the tuning parameter `K`, the calculation fails and returns `nan`. Ideally, we would do one of two things:

1. Emit a `RuntimeWarning` or even a `ValueError`. 
2. Iteratively try lower values of `K` until it returns a valid result, and probably also emit a `RuntimeWarning`.

I think @jkbren prefers the latter since it's easier to incorporate into our workflow, but open to either.

**Comment by leotrs** [comment]
I vote for 1.

**Comment by sdmccabe** [comment]
`RuntimeWarning` or `ValueError`?

**Comment by leotrs** [comment]
RuntimeWarning

**Comment by sdmccabe** [comment]
I can't reproduce this error. It may have been a holdover from an older version, since we encountered it in an earlier stage of the `wegd` experiments. If it turns up again, I'll add a `RuntimeWarning`.
