### ISSUE TITLE
LGTM results/integration

### ISSUE THREAD

**Issue by sdmccabe** [netsiphd/netrd#318]
I ran the repo through LGTM a while back, and the results are [here](https://lgtm.com/projects/g/netsiphd/netrd/?mode=list). Most of these are pretty easy fixes. 

I think it might also make sense to add the integration to avoid having these things pile up.

**Comment by sdmccabe** [comment]
@leotrs I think you had mentioned some other automated code review integration.

**Comment by leotrs** [comment]
https://www.codefactor.io/

**Comment by sdmccabe** [comment]
[Here](https://www.codefactor.io/repository/github/netsiphd/netrd/issues) are the Codefactor results. Less about unused imports, a bit more substantive.

Maybe instead of adding another integration, we just add a check in the existing test suite to use flake8 to catch unused imports, then add to that as needed?

**Comment by leotrs** [comment]
Yes, sounds good. Also, Codefactor can become very fussy, especially when taking contributions from many people who are not all on the same page about code standards/quality/practices/etc.

**Comment by sdmccabe** [comment]
Conveniently, I missed an unused import for us to try out the flake8 integration on...

**Comment by sdmccabe** [comment]
Think this is largely resolved by #319 and #320; we can revisit later if wanted.
