### ISSUE TITLE
Reduce the data size in tests

### ISSUE THREAD

**Issue by sdmccabe** [netsiphd/netrd#42]
Locally testing the partial correlation functions, I'm hitting a snag due to the sheer time it takes to run the tests. (The complexity here must be terrible.) In general, while a (1000, 500) matrix isn't terribly large, for the sorts of tests we're running we don't need that much data. I'd propose dropping the 1000 from the `[10, 100, 1000]` range of graph sizes we're testing, and drop $L$ from 500 to 200.

**Comment by leotrs** [comment]
Go for it.
