### ISSUE TITLE
Need longer time series to test graph size for reconstruction methods

### ISSUE THREAD

**Issue by chiahungyang** [netsiphd/netrd#55]
Hi all, the convergent cross-mapping algorithm has certain requirment of time series length (a lower bound). Currently in `test_reconstruction.py` the `test_graph_size` function tests 100 nodes on length-200 time series data, which is fewer than the required lower bound.

Can we change that to 250 time steps?

**Comment by leotrs** [comment]
@chiahungyang do you want to implement this? You can commit it along with your main PR.

**Comment by chiahungyang** [comment]
Definitely. I will make the changes.
