### ISSUE TITLE
Wrapper to rescale the output of graph distance methods

### ISSUE THREAD

**Issue by gstonge** [netsiphd/netrd#56]
The graph distance methods output a real positive number that is not identically upper-bounded. We could implement a wrapper, specific to the type of networks considered, that rescale the output of graph distance method by the "worst case scenario". For instance, for undirected simple networks, we could force that each graph distance method output "1" if it compares the empty graph of size N with the complete graph of size N.

**Comment by sdmccabe** [comment]
#118 implements a method for standardizing graph distances. Does that resolve this issue?

**Comment by gstonge** [comment]
Yes this seems to be a good way to scale the methods against each other! As @tlarock mentioned "We imagine more of these sorts of standardization values", so it is up to you if you want to keep this issue or open new ones for other specific standardization values.

One other standardization value I think could be useful is a slightly modified version of the one already implemented by @tlarock : Instead of comparing samples of the GNP against themselves, we could compare samples of the GNP against an empty graph. For the first (GNP graphs against themselves), I think local metrics (e.g. Hamming) will give a relatively "larger" average distance than spectral methods that are unaffected by isomorphisms. For the second (GNP graphs against empty), all methods should return a relatively "large" average distance, which could be helpful to "scale" the measures. If I remember well, @leotrs had some concerns about such approach though, but I can't remember what it was exactly.

**Comment by leotrs** [comment]
I was worried about comparing empty graphs vs complete graphs. I think using GNP graphs for standardization purposes is better.

**Comment by sdmccabe** [comment]
As I note in #140, not all the methods work on empty graphs (JSD of the degree distribution also doesn't work, based on my own tinkering), which makes using empty graphs for a standardization rather tricky.

**Comment by gstonge** [comment]
I see, good point. Out of curiosity I also compared an empty graph with GNP ones using the onion divergence. For distributions related to nodes, I always obtain 1, while for distribution related to edges, I always obtain 0.5, for any realization of the GNP. So, even if it returns a result, it doesn't help much with standardizing distance. I'm fine with closing the issue, thanks for the feedback!
