### ISSUE TITLE
Directory for experimental code and scripts

### ISSUE THREAD

**Issue by tlarock** [netsiphd/netrd#60]
Should code for the experimental pipeline go in its own top-level directory? Or do we want to provide a pipeline as part of the package itself? 

I am planning to start with everything about experiments at the top-level in a directory called "scripts", then we can decide later whether it will be useful to integrate pieces of it into the package.

**Comment by leotrs** [comment]
I don't think it should be part of the package. Maybe some of the functions we write for the pipeline can go in `netrd/utilities` in the end. Anything that lies outside of `netrd` won't be in the package so I agree let's just put everything inside a new `scripts/`.
