### ISSUE TITLE
Utility functions for input/output of data

### ISSUE THREAD

**Issue by tlarock** [netsiphd/netrd#61]
It would be nice to have functions in `utilities` that can read data, but for that we need to specify what format we want data to be in. It looks like the data in the data/ directory is exactly an NxL matrix in csv, where N is the number of nodes and L is the length of the time series. I think this is reasonable and I can add a simple function that just uses `numpy` to read this in, that way the user only needs to import `netrd` and not `numpy` separately to run our code. Similarly we could wrap the graph reading functions from `networkx`. Any objections/vitriol to hurl at this suggestion?

**Comment by leotrs** [comment]
Is the only outcome of this that the user needs one fewer `import`? In that case, I'd say let's not implement this right now.
