### ISSUE TITLE
Having trouble calling reconstruction methods

### ISSUE THREAD

**Issue by dsaffo** [netsiphd/netrd#62]
>>> import netrd
>>> x = netrd.reconstruction.random()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'module' object is not callable

keep getting this error when trying to call the reconstruction method, I've tried uninstalling and reinstalling with pip but not sure what to do from here

**Comment by tlarock** [comment]
What directory are you calling this from? Try calling it from outside of the project, e.g. first do `cd ~`, then `python`, then run the same code.

**Comment by leotrs** [comment]
The right way to use this is `netrd.reconstruction.RandomReconstruction`.

**Comment by dsaffo** [comment]
got it
