### ISSUE TITLE
Does`jaccard_similarity_score` in `jaccard_distance` require binary matrices?

### ISSUE THREAD

**Issue by tlarock** [netsiphd/netrd#65]
I am trying to use the output of `CorrelationMatrixReconstructor.fit` as an input to `JaccardDistance.dist`, but I am getting `ValueError: Can't handle mix of multilabel-indicator and continuous-multioutput` from `scikitlearn`. I think this is because Jaccard will only work for binary matrices. Is this true? If so, we need to decide how we will address it. @dsaffo what do you think? https://github.com/netsiphd/netrd/blob/72ee3ecdb3bf2fa0169263904cfd52676618b7f6/netrd/distance/jaccard_distance.py#L42

**Comment by sdmccabe** [comment]
Can we just make the matrices binary before calling `jaccard_similarity_score`?

**Comment by sdmccabe** [comment]
Is it? Each reconstruction method is returning a graph, with or without weights. We'd just be ignoring the weights in the distance measure.

**Comment by tlarock** [comment]
Yeah, that's fair. I didn't threshold the edges, so I was thinking that needed to be done, but it should be done outside the call to distance for sure. I'll binarize them in `jaccard_distance`.

**Comment by sdmccabe** [comment]
Resolved by #67.
