### ISSUE TITLE
Warnings for graph coercion

### ISSUE THREAD

**Issue by sdmccabe** [netsiphd/netrd#76]
Some of the methods want undirected graphs (see #74), and we typically have data or graphs that are directed, implicitly or explicitly. We should have some procedure for dealing with this case. I see five possibilities:

1. Always raise errors when the method receives directed data (as we did before #74).
2. Silently coerce a directed graph to undirected (as we do in #74).
3. Coerce with a printed message.
4. Coerce with a warning using the `warnings` library.
5. Add a `force_undirected` parameter to the relevant methods.

**Comment by leotrs** [comment]
I vote for number 4. Number 5 would only work if the methods can actually handle both directed and undirected graphs.

**Comment by tlarock** [comment]
I think we have a nice solution to this now (the below code), but we should probably put it in a utility function (I just told #119 to copy/paste code...). 

https://github.com/netsiphd/netrd/blob/357f4a958cb10aab371350687a9ca5b72046e8de/netrd/distance/resistance_perturbation.py#L57-L68

**Comment by tlarock** [comment]
Update: I have a function written, but I already have a pull request pending and don't feel like making the effort to branch. Will push a solution once my other pull request is resolved.

**Comment by sdmccabe** [comment]
Resolved by #125.
