### ISSUE TITLE
Consistent interface for (directed) graph creation

### ISSUE THREAD

**Issue by sdmccabe** [netsiphd/netrd#78]
This toy example suggests a problem with our current approach to creating graphs:

```python
In [13]: A = np.array([[0,1,0],[1,0,1],[0,0,0]])                                                                                                                                               

In [14]: A                                                                                                                                                                                     
Out[14]: 
array([[0, 1, 0],
       [1, 0, 1],
       [0, 0, 0]])

In [15]: import networkx as nx                                                                                                                                                                 

In [16]: G = nx.from_numpy_array(A)                                                                                                                                                            

In [17]: G.is_directed()                                                                                                                                                                       
Out[17]: False
```

It seems that if we have an asymmetric matrix we need to be explicit about using the `nx.DiGraph` constructor.

A utility function for determining which graph constructor to use (and performing other potentially useful preprocessing, like removing self-loops) would probably be useful here.

**Comment by sdmccabe** [comment]
There's now a function to do this; the second part of the issue was proposing to enforce consistency by actually using it. Does this seem like a reasonable thing to do? The PR would touch a lot of files. (I've done it locally and everything still passes---and I suspect one or two of the methods are unintentionally creating undirected graphs, which this would fix.)

@leotrs @tlarock

**Comment by tlarock** [comment]
I think it is both reasonable and necessary

**Comment by leotrs** [comment]
Apparently, `nx.from_numpy_array` was added on NetworkX version 2.2. Our `requirements.txt` asks for 2.0.0. Do we want to enforce 2.2?

**Comment by leotrs** [comment]
Coming around to it, if we are requiring 2.0, it's not too much of a jump to require 2.2 instead. It would be a problem if we were bumping from 1.x to 2.x. So let's see the PR and require 2.2.

**Comment by sdmccabe** [comment]
Making explicitly a conversation with @leotrs: I'm not sure that `from_numpy_array` strictly requires networkx 2.2, but the arguments I'm passing to the `create_using` parameter follow a style used in 2.2. If need be, I suspect we can rewrite some things to be 2.0-compatible, but for the sake of simplicity let's just bump the requirements for now. (Networkx 2.3 will be out soon anyway.)

**Comment by sdmccabe** [comment]
@jkbren @tlarock Note that now that this is merged it might affect the distance heatmaps. Let me know if something has dramatically changed.
