### ISSUE TITLE
netrdExplorer depends on pyct

### ISSUE THREAD

**Issue by sdmccabe** [netsiphd/netrd#92]
On my system (running Linux w/Anaconda), creating the bokeh application initially threw an exception because of an unfulfilled dependency on `pyct`. It seems odd that `panel` would raise an exception for a missing dependency instead of simply making it an explicit dependency of the package, but I guess that's what happened.

**Comment by sdmccabe** [comment]
Perhaps we should just add a separate `requirements.txt` to `notebooks/` to cover visualization libraries?

**Comment by leotrs** [comment]
We can close this since we have the awesome https://netrdexplorer.herokuapp.com

**Comment by leotrs** [comment]
We can close this since we have the awesome https://netrdexplorer.herokuapp.com
